### ISSUE TITLE
[Linux] Save-Module doesn't work due to capitalization errors

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSResourceGet#123]
https://github.com/PowerShell/PowerShellGet/blob/3fcd36daa574d51a19b17fcad0694069725f0392/src/SavePSResource.cs#L440-L445

This breaks on Linux because the folder gets created as lowercase but when it tries to move the files it's looking for the cased name of the folder.

![image](https://user-images.githubusercontent.com/15258962/79355516-9e39e080-7ef2-11ea-95fc-e1b744aabaeb.png)
![image](https://user-images.githubusercontent.com/15258962/79355577-b578ce00-7ef2-11ea-86a8-4a20b5811c14.png)

**Comment by alerickson** [comment]
This should be resolved with the latest release.  Please open again if it's not

**Comment by JustinGrote** [comment]
@alerickson still an issue with Beta3 and the sha512 file
![image](https://user-images.githubusercontent.com/15258962/82100576-cddd3380-96be-11ea-827f-2be71f4264b0.png)
